inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/teaspoon_env.rb'
    - 'storage/**/*'
    - 'vendor/**/*'
    - 'app/controllers/concerns/action_controller/**/*'

Rails:
  Enabled: true

Metrics/ClassLength:
  Exclude:
    - 'app/services/marc_record_service.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'

Layout/LineLength:
  Max: 130

Metrics/MethodLength:
  Exclude:
    - 'app/models/ability.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/models/ability.rb'

RSpec/MultipleMemoizedHelpers:
  Max: 10
